/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DasboardAppRouteImport } from './routes/dasboard/app'
import { Route as ApiTeamRouteImport } from './routes/api/team'
import { Route as ApiTaskRouteImport } from './routes/api/task'
import { Route as DasboardSettingsSettingRouteImport } from './routes/dasboard/settings/setting'
import { Route as DasboardEmployeeEmployeeRouteImport } from './routes/dasboard/employee/employee'
import { Route as DasboardEmployeeIdRouteImport } from './routes/dasboard/employee/$id'
import { Route as ApiEmployeeWarnRouteImport } from './routes/api/employee/warn'
import { Route as ApiEmployeeToggleRouteImport } from './routes/api/employee/toggle'
import { Route as ApiEmployeeProgressRouteImport } from './routes/api/employee/progress'
import { Route as ApiEmployeeMeRouteImport } from './routes/api/employee/me'
import { Route as ApiEmployeeGetRouteImport } from './routes/api/employee/get'
import { Route as ApiEmployeeCreateRouteImport } from './routes/api/employee/create'
import { Route as ApiEmployeeAssignChecklistRouteImport } from './routes/api/employee/assign-checklist'
import { Route as ApiEmployeeAllWithProgressRouteImport } from './routes/api/employee/all-with-progress'
import { Route as ApiEmployeeAddToggleRouteImport } from './routes/api/employee/add-toggle'
import { Route as ApiEmployeeIdRouteImport } from './routes/api/employee/$id'
import { Route as ApiDocumentUploadRouteImport } from './routes/api/document/upload'
import { Route as ApiDocumentRespondRouteImport } from './routes/api/document/respond'
import { Route as ApiDocumentGetRouteImport } from './routes/api/document/get'
import { Route as ApiChecklistGetRouteImport } from './routes/api/checklist/get'
import { Route as ApiChecklistDeleteRouteImport } from './routes/api/checklist/delete'
import { Route as ApiChecklistCreateRouteImport } from './routes/api/checklist/create'
import { Route as ApiChecklistAddItemRouteImport } from './routes/api/checklist/add-item'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DasboardAppRoute = DasboardAppRouteImport.update({
  id: '/dasboard/app',
  path: '/dasboard/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamRoute = ApiTeamRouteImport.update({
  id: '/api/team',
  path: '/api/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskRoute = ApiTaskRouteImport.update({
  id: '/api/task',
  path: '/api/task',
  getParentRoute: () => rootRouteImport,
} as any)
const DasboardSettingsSettingRoute = DasboardSettingsSettingRouteImport.update({
  id: '/dasboard/settings/setting',
  path: '/dasboard/settings/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const DasboardEmployeeEmployeeRoute =
  DasboardEmployeeEmployeeRouteImport.update({
    id: '/dasboard/employee/employee',
    path: '/dasboard/employee/employee',
    getParentRoute: () => rootRouteImport,
  } as any)
const DasboardEmployeeIdRoute = DasboardEmployeeIdRouteImport.update({
  id: '/dasboard/employee/$id',
  path: '/dasboard/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeWarnRoute = ApiEmployeeWarnRouteImport.update({
  id: '/api/employee/warn',
  path: '/api/employee/warn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeToggleRoute = ApiEmployeeToggleRouteImport.update({
  id: '/api/employee/toggle',
  path: '/api/employee/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeProgressRoute = ApiEmployeeProgressRouteImport.update({
  id: '/api/employee/progress',
  path: '/api/employee/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeMeRoute = ApiEmployeeMeRouteImport.update({
  id: '/api/employee/me',
  path: '/api/employee/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeGetRoute = ApiEmployeeGetRouteImport.update({
  id: '/api/employee/get',
  path: '/api/employee/get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeCreateRoute = ApiEmployeeCreateRouteImport.update({
  id: '/api/employee/create',
  path: '/api/employee/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeAssignChecklistRoute =
  ApiEmployeeAssignChecklistRouteImport.update({
    id: '/api/employee/assign-checklist',
    path: '/api/employee/assign-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmployeeAllWithProgressRoute =
  ApiEmployeeAllWithProgressRouteImport.update({
    id: '/api/employee/all-with-progress',
    path: '/api/employee/all-with-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmployeeAddToggleRoute = ApiEmployeeAddToggleRouteImport.update({
  id: '/api/employee/add-toggle',
  path: '/api/employee/add-toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeIdRoute = ApiEmployeeIdRouteImport.update({
  id: '/api/employee/$id',
  path: '/api/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentUploadRoute = ApiDocumentUploadRouteImport.update({
  id: '/api/document/upload',
  path: '/api/document/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentRespondRoute = ApiDocumentRespondRouteImport.update({
  id: '/api/document/respond',
  path: '/api/document/respond',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentGetRoute = ApiDocumentGetRouteImport.update({
  id: '/api/document/get',
  path: '/api/document/get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistGetRoute = ApiChecklistGetRouteImport.update({
  id: '/api/checklist/get',
  path: '/api/checklist/get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistDeleteRoute = ApiChecklistDeleteRouteImport.update({
  id: '/api/checklist/delete',
  path: '/api/checklist/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistCreateRoute = ApiChecklistCreateRouteImport.update({
  id: '/api/checklist/create',
  path: '/api/checklist/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistAddItemRoute = ApiChecklistAddItemRouteImport.update({
  id: '/api/checklist/add-item',
  path: '/api/checklist/add-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/task': typeof ApiTaskRoute
  '/api/team': typeof ApiTeamRoute
  '/dasboard/app': typeof DasboardAppRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/checklist/add-item': typeof ApiChecklistAddItemRoute
  '/api/checklist/create': typeof ApiChecklistCreateRoute
  '/api/checklist/delete': typeof ApiChecklistDeleteRoute
  '/api/checklist/get': typeof ApiChecklistGetRoute
  '/api/document/get': typeof ApiDocumentGetRoute
  '/api/document/respond': typeof ApiDocumentRespondRoute
  '/api/document/upload': typeof ApiDocumentUploadRoute
  '/api/employee/$id': typeof ApiEmployeeIdRoute
  '/api/employee/add-toggle': typeof ApiEmployeeAddToggleRoute
  '/api/employee/all-with-progress': typeof ApiEmployeeAllWithProgressRoute
  '/api/employee/assign-checklist': typeof ApiEmployeeAssignChecklistRoute
  '/api/employee/create': typeof ApiEmployeeCreateRoute
  '/api/employee/get': typeof ApiEmployeeGetRoute
  '/api/employee/me': typeof ApiEmployeeMeRoute
  '/api/employee/progress': typeof ApiEmployeeProgressRoute
  '/api/employee/toggle': typeof ApiEmployeeToggleRoute
  '/api/employee/warn': typeof ApiEmployeeWarnRoute
  '/dasboard/employee/$id': typeof DasboardEmployeeIdRoute
  '/dasboard/employee/employee': typeof DasboardEmployeeEmployeeRoute
  '/dasboard/settings/setting': typeof DasboardSettingsSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/task': typeof ApiTaskRoute
  '/api/team': typeof ApiTeamRoute
  '/dasboard/app': typeof DasboardAppRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/checklist/add-item': typeof ApiChecklistAddItemRoute
  '/api/checklist/create': typeof ApiChecklistCreateRoute
  '/api/checklist/delete': typeof ApiChecklistDeleteRoute
  '/api/checklist/get': typeof ApiChecklistGetRoute
  '/api/document/get': typeof ApiDocumentGetRoute
  '/api/document/respond': typeof ApiDocumentRespondRoute
  '/api/document/upload': typeof ApiDocumentUploadRoute
  '/api/employee/$id': typeof ApiEmployeeIdRoute
  '/api/employee/add-toggle': typeof ApiEmployeeAddToggleRoute
  '/api/employee/all-with-progress': typeof ApiEmployeeAllWithProgressRoute
  '/api/employee/assign-checklist': typeof ApiEmployeeAssignChecklistRoute
  '/api/employee/create': typeof ApiEmployeeCreateRoute
  '/api/employee/get': typeof ApiEmployeeGetRoute
  '/api/employee/me': typeof ApiEmployeeMeRoute
  '/api/employee/progress': typeof ApiEmployeeProgressRoute
  '/api/employee/toggle': typeof ApiEmployeeToggleRoute
  '/api/employee/warn': typeof ApiEmployeeWarnRoute
  '/dasboard/employee/$id': typeof DasboardEmployeeIdRoute
  '/dasboard/employee/employee': typeof DasboardEmployeeEmployeeRoute
  '/dasboard/settings/setting': typeof DasboardSettingsSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/task': typeof ApiTaskRoute
  '/api/team': typeof ApiTeamRoute
  '/dasboard/app': typeof DasboardAppRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/checklist/add-item': typeof ApiChecklistAddItemRoute
  '/api/checklist/create': typeof ApiChecklistCreateRoute
  '/api/checklist/delete': typeof ApiChecklistDeleteRoute
  '/api/checklist/get': typeof ApiChecklistGetRoute
  '/api/document/get': typeof ApiDocumentGetRoute
  '/api/document/respond': typeof ApiDocumentRespondRoute
  '/api/document/upload': typeof ApiDocumentUploadRoute
  '/api/employee/$id': typeof ApiEmployeeIdRoute
  '/api/employee/add-toggle': typeof ApiEmployeeAddToggleRoute
  '/api/employee/all-with-progress': typeof ApiEmployeeAllWithProgressRoute
  '/api/employee/assign-checklist': typeof ApiEmployeeAssignChecklistRoute
  '/api/employee/create': typeof ApiEmployeeCreateRoute
  '/api/employee/get': typeof ApiEmployeeGetRoute
  '/api/employee/me': typeof ApiEmployeeMeRoute
  '/api/employee/progress': typeof ApiEmployeeProgressRoute
  '/api/employee/toggle': typeof ApiEmployeeToggleRoute
  '/api/employee/warn': typeof ApiEmployeeWarnRoute
  '/dasboard/employee/$id': typeof DasboardEmployeeIdRoute
  '/dasboard/employee/employee': typeof DasboardEmployeeEmployeeRoute
  '/dasboard/settings/setting': typeof DasboardSettingsSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/task'
    | '/api/team'
    | '/dasboard/app'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/checklist/add-item'
    | '/api/checklist/create'
    | '/api/checklist/delete'
    | '/api/checklist/get'
    | '/api/document/get'
    | '/api/document/respond'
    | '/api/document/upload'
    | '/api/employee/$id'
    | '/api/employee/add-toggle'
    | '/api/employee/all-with-progress'
    | '/api/employee/assign-checklist'
    | '/api/employee/create'
    | '/api/employee/get'
    | '/api/employee/me'
    | '/api/employee/progress'
    | '/api/employee/toggle'
    | '/api/employee/warn'
    | '/dasboard/employee/$id'
    | '/dasboard/employee/employee'
    | '/dasboard/settings/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/task'
    | '/api/team'
    | '/dasboard/app'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/checklist/add-item'
    | '/api/checklist/create'
    | '/api/checklist/delete'
    | '/api/checklist/get'
    | '/api/document/get'
    | '/api/document/respond'
    | '/api/document/upload'
    | '/api/employee/$id'
    | '/api/employee/add-toggle'
    | '/api/employee/all-with-progress'
    | '/api/employee/assign-checklist'
    | '/api/employee/create'
    | '/api/employee/get'
    | '/api/employee/me'
    | '/api/employee/progress'
    | '/api/employee/toggle'
    | '/api/employee/warn'
    | '/dasboard/employee/$id'
    | '/dasboard/employee/employee'
    | '/dasboard/settings/setting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/task'
    | '/api/team'
    | '/dasboard/app'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/checklist/add-item'
    | '/api/checklist/create'
    | '/api/checklist/delete'
    | '/api/checklist/get'
    | '/api/document/get'
    | '/api/document/respond'
    | '/api/document/upload'
    | '/api/employee/$id'
    | '/api/employee/add-toggle'
    | '/api/employee/all-with-progress'
    | '/api/employee/assign-checklist'
    | '/api/employee/create'
    | '/api/employee/get'
    | '/api/employee/me'
    | '/api/employee/progress'
    | '/api/employee/toggle'
    | '/api/employee/warn'
    | '/dasboard/employee/$id'
    | '/dasboard/employee/employee'
    | '/dasboard/settings/setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiTaskRoute: typeof ApiTaskRoute
  ApiTeamRoute: typeof ApiTeamRoute
  DasboardAppRoute: typeof DasboardAppRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiChecklistAddItemRoute: typeof ApiChecklistAddItemRoute
  ApiChecklistCreateRoute: typeof ApiChecklistCreateRoute
  ApiChecklistDeleteRoute: typeof ApiChecklistDeleteRoute
  ApiChecklistGetRoute: typeof ApiChecklistGetRoute
  ApiDocumentGetRoute: typeof ApiDocumentGetRoute
  ApiDocumentRespondRoute: typeof ApiDocumentRespondRoute
  ApiDocumentUploadRoute: typeof ApiDocumentUploadRoute
  ApiEmployeeIdRoute: typeof ApiEmployeeIdRoute
  ApiEmployeeAddToggleRoute: typeof ApiEmployeeAddToggleRoute
  ApiEmployeeAllWithProgressRoute: typeof ApiEmployeeAllWithProgressRoute
  ApiEmployeeAssignChecklistRoute: typeof ApiEmployeeAssignChecklistRoute
  ApiEmployeeCreateRoute: typeof ApiEmployeeCreateRoute
  ApiEmployeeGetRoute: typeof ApiEmployeeGetRoute
  ApiEmployeeMeRoute: typeof ApiEmployeeMeRoute
  ApiEmployeeProgressRoute: typeof ApiEmployeeProgressRoute
  ApiEmployeeToggleRoute: typeof ApiEmployeeToggleRoute
  ApiEmployeeWarnRoute: typeof ApiEmployeeWarnRoute
  DasboardEmployeeIdRoute: typeof DasboardEmployeeIdRoute
  DasboardEmployeeEmployeeRoute: typeof DasboardEmployeeEmployeeRoute
  DasboardSettingsSettingRoute: typeof DasboardSettingsSettingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasboard/app': {
      id: '/dasboard/app'
      path: '/dasboard/app'
      fullPath: '/dasboard/app'
      preLoaderRoute: typeof DasboardAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team': {
      id: '/api/team'
      path: '/api/team'
      fullPath: '/api/team'
      preLoaderRoute: typeof ApiTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task': {
      id: '/api/task'
      path: '/api/task'
      fullPath: '/api/task'
      preLoaderRoute: typeof ApiTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasboard/settings/setting': {
      id: '/dasboard/settings/setting'
      path: '/dasboard/settings/setting'
      fullPath: '/dasboard/settings/setting'
      preLoaderRoute: typeof DasboardSettingsSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasboard/employee/employee': {
      id: '/dasboard/employee/employee'
      path: '/dasboard/employee/employee'
      fullPath: '/dasboard/employee/employee'
      preLoaderRoute: typeof DasboardEmployeeEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasboard/employee/$id': {
      id: '/dasboard/employee/$id'
      path: '/dasboard/employee/$id'
      fullPath: '/dasboard/employee/$id'
      preLoaderRoute: typeof DasboardEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/warn': {
      id: '/api/employee/warn'
      path: '/api/employee/warn'
      fullPath: '/api/employee/warn'
      preLoaderRoute: typeof ApiEmployeeWarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/toggle': {
      id: '/api/employee/toggle'
      path: '/api/employee/toggle'
      fullPath: '/api/employee/toggle'
      preLoaderRoute: typeof ApiEmployeeToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/progress': {
      id: '/api/employee/progress'
      path: '/api/employee/progress'
      fullPath: '/api/employee/progress'
      preLoaderRoute: typeof ApiEmployeeProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/me': {
      id: '/api/employee/me'
      path: '/api/employee/me'
      fullPath: '/api/employee/me'
      preLoaderRoute: typeof ApiEmployeeMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/get': {
      id: '/api/employee/get'
      path: '/api/employee/get'
      fullPath: '/api/employee/get'
      preLoaderRoute: typeof ApiEmployeeGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/create': {
      id: '/api/employee/create'
      path: '/api/employee/create'
      fullPath: '/api/employee/create'
      preLoaderRoute: typeof ApiEmployeeCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/assign-checklist': {
      id: '/api/employee/assign-checklist'
      path: '/api/employee/assign-checklist'
      fullPath: '/api/employee/assign-checklist'
      preLoaderRoute: typeof ApiEmployeeAssignChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/all-with-progress': {
      id: '/api/employee/all-with-progress'
      path: '/api/employee/all-with-progress'
      fullPath: '/api/employee/all-with-progress'
      preLoaderRoute: typeof ApiEmployeeAllWithProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/add-toggle': {
      id: '/api/employee/add-toggle'
      path: '/api/employee/add-toggle'
      fullPath: '/api/employee/add-toggle'
      preLoaderRoute: typeof ApiEmployeeAddToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee/$id': {
      id: '/api/employee/$id'
      path: '/api/employee/$id'
      fullPath: '/api/employee/$id'
      preLoaderRoute: typeof ApiEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/upload': {
      id: '/api/document/upload'
      path: '/api/document/upload'
      fullPath: '/api/document/upload'
      preLoaderRoute: typeof ApiDocumentUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/respond': {
      id: '/api/document/respond'
      path: '/api/document/respond'
      fullPath: '/api/document/respond'
      preLoaderRoute: typeof ApiDocumentRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/get': {
      id: '/api/document/get'
      path: '/api/document/get'
      fullPath: '/api/document/get'
      preLoaderRoute: typeof ApiDocumentGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklist/get': {
      id: '/api/checklist/get'
      path: '/api/checklist/get'
      fullPath: '/api/checklist/get'
      preLoaderRoute: typeof ApiChecklistGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklist/delete': {
      id: '/api/checklist/delete'
      path: '/api/checklist/delete'
      fullPath: '/api/checklist/delete'
      preLoaderRoute: typeof ApiChecklistDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklist/create': {
      id: '/api/checklist/create'
      path: '/api/checklist/create'
      fullPath: '/api/checklist/create'
      preLoaderRoute: typeof ApiChecklistCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklist/add-item': {
      id: '/api/checklist/add-item'
      path: '/api/checklist/add-item'
      fullPath: '/api/checklist/add-item'
      preLoaderRoute: typeof ApiChecklistAddItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiTaskRoute: ApiTaskRoute,
  ApiTeamRoute: ApiTeamRoute,
  DasboardAppRoute: DasboardAppRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiChecklistAddItemRoute: ApiChecklistAddItemRoute,
  ApiChecklistCreateRoute: ApiChecklistCreateRoute,
  ApiChecklistDeleteRoute: ApiChecklistDeleteRoute,
  ApiChecklistGetRoute: ApiChecklistGetRoute,
  ApiDocumentGetRoute: ApiDocumentGetRoute,
  ApiDocumentRespondRoute: ApiDocumentRespondRoute,
  ApiDocumentUploadRoute: ApiDocumentUploadRoute,
  ApiEmployeeIdRoute: ApiEmployeeIdRoute,
  ApiEmployeeAddToggleRoute: ApiEmployeeAddToggleRoute,
  ApiEmployeeAllWithProgressRoute: ApiEmployeeAllWithProgressRoute,
  ApiEmployeeAssignChecklistRoute: ApiEmployeeAssignChecklistRoute,
  ApiEmployeeCreateRoute: ApiEmployeeCreateRoute,
  ApiEmployeeGetRoute: ApiEmployeeGetRoute,
  ApiEmployeeMeRoute: ApiEmployeeMeRoute,
  ApiEmployeeProgressRoute: ApiEmployeeProgressRoute,
  ApiEmployeeToggleRoute: ApiEmployeeToggleRoute,
  ApiEmployeeWarnRoute: ApiEmployeeWarnRoute,
  DasboardEmployeeIdRoute: DasboardEmployeeIdRoute,
  DasboardEmployeeEmployeeRoute: DasboardEmployeeEmployeeRoute,
  DasboardSettingsSettingRoute: DasboardSettingsSettingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
